import ArgumentParser
import Foundation

/// Generates a buildable `.xcodeproj` inside an existing folder of Swift
/// sources. Pairs with the recovery banner in the Mac app: when a user opens
/// a folder another AI tool left without a project, the banner offers either
/// a one-click Quick Scaffold (uses the Mac-side scaffolder directly) or
/// hands off to Claude Code, which calls THIS command from Bash.
///
/// The pbxproj template here is intentionally a duplicate of
/// `Templates.wrapProjectPBXProj` in `XcodeProjectScaffolder.swift` — that
/// type is internal to the Mac app target and can't be imported from this
/// Swift Package. Both write the same Xcode 16 synced-root layout, so a
/// project generated by either tool opens and builds identically.
@available(macOS 10.15, macCatalyst 13, iOS 13, tvOS 13, watchOS 6, *)
struct GenerateXcodeProject: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "generate-xcodeproj",
        abstract: "Create a buildable Xcode project for a folder of Swift sources.",
        discussion: """
        Wraps an existing folder of Swift files with a `.xcodeproj` so it can
        be built by Xcode or `xcodebuild`. Useful when another AI coding tool
        generated loose Swift files without setting up a project.

        Uses Xcode 16's synchronized root groups, so new Swift files added
        later are picked up automatically — you don't need to re-run this
        when you add files.

        Examples:
          lingcode generate-xcodeproj                          # current folder
          lingcode generate-xcodeproj ~/Desktop/OpenConnect
          lingcode generate-xcodeproj --platform ios --name MyApp --bundle-id com.you.MyApp
        """
    )

    @Argument(help: "Folder containing Swift sources (default: current directory).")
    var path: String?

    @Option(name: [.customLong("name")], help: "Product / target name (default: folder name).")
    var productName: String?

    @Option(name: [.customLong("bundle-id"), .customShort("b")], help: "Bundle identifier (default: com.example.<name>).")
    var bundleId: String?

    @Option(name: [.customLong("platform"), .customShort("p")], help: "Platform: macos, ios, or tvos (default: inferred from sources).")
    var platform: String?

    @Flag(name: .long, help: "Overwrite an existing .xcodeproj at the destination.")
    var overwrite: Bool = false

    func run() async throws {
        let fm = FileManager.default

        let folder: URL = {
            if let p = path, !p.isEmpty {
                return URL(fileURLWithPath: (p as NSString).expandingTildeInPath)
            }
            return URL(fileURLWithPath: fm.currentDirectoryPath)
        }()

        var isDir: ObjCBool = false
        guard fm.fileExists(atPath: folder.path, isDirectory: &isDir), isDir.boolValue else {
            try errOut("lingcode generate-xcodeproj: \(folder.path) is not a folder")
            throw ExitCode(2)
        }

        let swiftFiles = collectSwiftFiles(under: folder, limit: 200)
        guard !swiftFiles.isEmpty else {
            try errOut("lingcode generate-xcodeproj: no .swift files found under \(folder.path)")
            throw ExitCode(2)
        }

        let resolvedName = sanitizeProductName(productName ?? folder.lastPathComponent)
        guard !resolvedName.isEmpty else {
            try errOut("lingcode generate-xcodeproj: folder name doesn't yield a valid product name; use --name to set one")
            throw ExitCode(2)
        }
        let resolvedBundle = bundleId ?? "com.example.\(resolvedName)"
        let resolvedPlatform = try resolvePlatform(swiftFiles: swiftFiles)

        let xcodeprojURL = folder.appendingPathComponent("\(resolvedName).xcodeproj")
        if fm.fileExists(atPath: xcodeprojURL.path) {
            if overwrite {
                try fm.removeItem(at: xcodeprojURL)
            } else {
                try errOut("lingcode generate-xcodeproj: \(xcodeprojURL.path) already exists. Pass --overwrite to replace it.")
                throw ExitCode(1)
            }
        }

        let schemesDir = xcodeprojURL.appendingPathComponent("xcshareddata/xcschemes")
        try fm.createDirectory(at: schemesDir, withIntermediateDirectories: true)

        let ids = PBXIds()
        let pbxproj = wrapProjectPBXProj(
            productName: resolvedName,
            bundleIdentifier: resolvedBundle,
            platform: resolvedPlatform,
            ids: ids
        )
        let scheme = schemeXML(
            productName: resolvedName,
            mainTargetID: ids.mainTarget
        )

        try pbxproj.write(
            to: xcodeprojURL.appendingPathComponent("project.pbxproj"),
            atomically: true,
            encoding: .utf8
        )
        try scheme.write(
            to: schemesDir.appendingPathComponent("\(resolvedName).xcscheme"),
            atomically: true,
            encoding: .utf8
        )

        Swift.print("✓ Wrote \(xcodeprojURL.path)")
        Swift.print("  target:    \(resolvedName)")
        Swift.print("  bundle:    \(resolvedBundle)")
        Swift.print("  platform:  \(resolvedPlatform == .iOS ? "ios" : "macos")")
        Swift.print("")
        Swift.print("Build with: xcodebuild -scheme \(resolvedName) -configuration Debug build")
    }

    // MARK: - Helpers

    private func errOut(_ msg: String) throws {
        FileHandle.standardError.write(Data((msg + "\n").utf8))
    }

    private func resolvePlatform(swiftFiles: [URL]) throws -> WrapPlatform {
        if let raw = platform?.lowercased() {
            switch raw {
            case "ios": return .iOS
            case "macos", "mac": return .macOS
            case "tvos", "tv": return .tvOS
            default:
                try errOut("lingcode generate-xcodeproj: unknown --platform '\(raw)' (expected 'macos', 'ios', or 'tvos')")
                throw ExitCode(2)
            }
        }
        return inferPlatform(swiftFiles: swiftFiles)
    }

    private func sanitizeProductName(_ raw: String) -> String {
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        let stripped = trimmed.replacingOccurrences(of: " ", with: "")
        return stripped
    }

    private func inferPlatform(swiftFiles: [URL], scanLimit: Int = 20) -> WrapPlatform {
        var votedIOS = false
        for url in swiftFiles.prefix(scanLimit) {
            guard let contents = try? String(contentsOf: url, encoding: .utf8) else { continue }
            // tvOS sources also `import UIKit`, so check the tvOS-only framework first.
            if contents.contains("import TVUIKit") || contents.contains("import TVMLKit") {
                return .tvOS
            }
            if contents.contains("import UIKit") || contents.contains("import WatchKit") {
                votedIOS = true
                break
            }
            if contents.contains("import AppKit") {
                return .macOS
            }
        }
        return votedIOS ? .iOS : .macOS
    }

    private func collectSwiftFiles(under root: URL, limit: Int) -> [URL] {
        let skip: Set<String> = [
            ".git", ".svn", ".hg",
            "node_modules", "build", ".build", "DerivedData",
            ".swiftpm", ".swiftpm-cache",
            "Pods", "Carthage",
            ".cache", ".derived-data",
        ]
        let fm = FileManager.default
        var results: [URL] = []
        var queue: [URL] = [root]
        while let dir = queue.first {
            queue.removeFirst()
            guard let children = try? fm.contentsOfDirectory(
                at: dir,
                includingPropertiesForKeys: [.isDirectoryKey],
                options: [.skipsHiddenFiles]
            ) else { continue }
            for url in children {
                if results.count >= limit { return results }
                var isDir: ObjCBool = false
                guard fm.fileExists(atPath: url.path, isDirectory: &isDir) else { continue }
                if isDir.boolValue {
                    let name = url.lastPathComponent
                    if skip.contains(name) { continue }
                    let ext = url.pathExtension.lowercased()
                    if ext == "xcodeproj" || ext == "xcworkspace" || ext == "xcassets" { continue }
                    queue.append(url)
                } else if url.pathExtension.lowercased() == "swift" {
                    results.append(url)
                }
            }
        }
        return results
    }
}

// MARK: - Standalone pbxproj writer
//
// The Mac app's `XcodeProjectScaffolder` does the same thing for in-app
// Quick Scaffold; we can't import it here (different target). Both stay in
// sync by producing the same Xcode 16 synced-root layout.

private enum WrapPlatform {
    case iOS
    case macOS
    case tvOS

    var sdkRoot: String {
        switch self {
        case .iOS: return "iphoneos"
        case .macOS: return "macosx"
        case .tvOS: return "appletvos"
        }
    }

    var supportedPlatforms: String {
        switch self {
        case .iOS: return "\"iphoneos iphonesimulator\""
        case .macOS: return "macosx"
        case .tvOS: return "\"appletvos appletvsimulator\""
        }
    }

    var targetedDeviceFamily: String {
        switch self {
        case .iOS: return "\"1,2\""
        case .macOS: return "\"\""
        case .tvOS: return "3"
        }
    }

    var deploymentTargetKey: String {
        switch self {
        case .iOS: return "IPHONEOS_DEPLOYMENT_TARGET"
        case .macOS: return "MACOSX_DEPLOYMENT_TARGET"
        case .tvOS: return "TVOS_DEPLOYMENT_TARGET"
        }
    }

    var deploymentTargetValue: String {
        switch self {
        case .iOS: return "17.0"
        case .macOS: return "14.0"
        case .tvOS: return "17.0"
        }
    }
}

private struct PBXIds {
    let project = Self.newID()
    let mainGroup = Self.newID()
    let productsGroup = Self.newID()
    let sourceSyncedGroup = Self.newID()
    let productRef = Self.newID()
    let mainTarget = Self.newID()
    let sourcesBuildPhase = Self.newID()
    let resourcesBuildPhase = Self.newID()
    let frameworksBuildPhase = Self.newID()
    let projectBuildConfigList = Self.newID()
    let projectDebugConfig = Self.newID()
    let projectReleaseConfig = Self.newID()
    let targetBuildConfigList = Self.newID()
    let targetDebugConfig = Self.newID()
    let targetReleaseConfig = Self.newID()

    static func newID() -> String {
        let raw = UUID().uuidString.replacingOccurrences(of: "-", with: "")
        return String(raw.prefix(24))
    }
}

private func wrapProjectPBXProj(productName: String,
                                bundleIdentifier: String,
                                platform: WrapPlatform,
                                ids: PBXIds) -> String {
    let productType = "com.apple.product-type.application"
    return """
    // !$*UTF8*$!
    {
    \tarchiveVersion = 1;
    \tclasses = {
    \t};
    \tobjectVersion = 77;
    \tobjects = {

    /* Begin PBXFileReference section */
    \t\t\(ids.productRef) /* \(productName).app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = \(productName).app; sourceTree = BUILT_PRODUCTS_DIR; };
    /* End PBXFileReference section */

    /* Begin PBXFileSystemSynchronizedRootGroup section */
    \t\t\(ids.sourceSyncedGroup) /* \(productName) */ = {isa = PBXFileSystemSynchronizedRootGroup; explicitFileTypes = {}; explicitFolders = (); path = .; sourceTree = "<group>"; };
    /* End PBXFileSystemSynchronizedRootGroup section */

    /* Begin PBXFrameworksBuildPhase section */
    \t\t\(ids.frameworksBuildPhase) /* Frameworks */ = {
    \t\t\tisa = PBXFrameworksBuildPhase;
    \t\t\tbuildActionMask = 2147483647;
    \t\t\tfiles = (
    \t\t\t);
    \t\t\trunOnlyForDeploymentPostprocessing = 0;
    \t\t};
    /* End PBXFrameworksBuildPhase section */

    /* Begin PBXGroup section */
    \t\t\(ids.mainGroup) = {
    \t\t\tisa = PBXGroup;
    \t\t\tchildren = (
    \t\t\t\t\(ids.sourceSyncedGroup) /* \(productName) */,
    \t\t\t\t\(ids.productsGroup) /* Products */,
    \t\t\t);
    \t\t\tsourceTree = "<group>";
    \t\t};
    \t\t\(ids.productsGroup) /* Products */ = {
    \t\t\tisa = PBXGroup;
    \t\t\tchildren = (
    \t\t\t\t\(ids.productRef) /* \(productName).app */,
    \t\t\t);
    \t\t\tname = Products;
    \t\t\tsourceTree = "<group>";
    \t\t};
    /* End PBXGroup section */

    /* Begin PBXNativeTarget section */
    \t\t\(ids.mainTarget) /* \(productName) */ = {
    \t\t\tisa = PBXNativeTarget;
    \t\t\tbuildConfigurationList = \(ids.targetBuildConfigList) /* Build configuration list for PBXNativeTarget "\(productName)" */;
    \t\t\tbuildPhases = (
    \t\t\t\t\(ids.sourcesBuildPhase) /* Sources */,
    \t\t\t\t\(ids.frameworksBuildPhase) /* Frameworks */,
    \t\t\t\t\(ids.resourcesBuildPhase) /* Resources */,
    \t\t\t);
    \t\t\tbuildRules = (
    \t\t\t);
    \t\t\tdependencies = (
    \t\t\t);
    \t\t\tfileSystemSynchronizedGroups = (
    \t\t\t\t\(ids.sourceSyncedGroup) /* \(productName) */,
    \t\t\t);
    \t\t\tname = \(productName);
    \t\t\tproductName = \(productName);
    \t\t\tproductReference = \(ids.productRef) /* \(productName).app */;
    \t\t\tproductType = "\(productType)";
    \t\t};
    /* End PBXNativeTarget section */

    /* Begin PBXProject section */
    \t\t\(ids.project) /* Project object */ = {
    \t\t\tisa = PBXProject;
    \t\t\tattributes = {
    \t\t\t\tBuildIndependentTargetsInParallel = 1;
    \t\t\t\tLastSwiftUpdateCheck = 1600;
    \t\t\t\tLastUpgradeCheck = 1600;
    \t\t\t\tTargetAttributes = {
    \t\t\t\t\t\(ids.mainTarget) = {
    \t\t\t\t\t\tCreatedOnToolsVersion = 16.0;
    \t\t\t\t\t};
    \t\t\t\t};
    \t\t\t};
    \t\t\tbuildConfigurationList = \(ids.projectBuildConfigList) /* Build configuration list for PBXProject "\(productName)" */;
    \t\t\tdevelopmentRegion = en;
    \t\t\thasScannedForEncodings = 0;
    \t\t\tknownRegions = (
    \t\t\t\ten,
    \t\t\t\tBase,
    \t\t\t);
    \t\t\tmainGroup = \(ids.mainGroup);
    \t\t\tminimizedProjectReferenceProxies = 1;
    \t\t\tpreferredProjectObjectVersion = 77;
    \t\t\tproductRefGroup = \(ids.productsGroup) /* Products */;
    \t\t\tprojectDirPath = "";
    \t\t\tprojectRoot = "";
    \t\t\ttargets = (
    \t\t\t\t\(ids.mainTarget) /* \(productName) */,
    \t\t\t);
    \t\t};
    /* End PBXProject section */

    /* Begin PBXResourcesBuildPhase section */
    \t\t\(ids.resourcesBuildPhase) /* Resources */ = {
    \t\t\tisa = PBXResourcesBuildPhase;
    \t\t\tbuildActionMask = 2147483647;
    \t\t\tfiles = (
    \t\t\t);
    \t\t\trunOnlyForDeploymentPostprocessing = 0;
    \t\t};
    /* End PBXResourcesBuildPhase section */

    /* Begin PBXSourcesBuildPhase section */
    \t\t\(ids.sourcesBuildPhase) /* Sources */ = {
    \t\t\tisa = PBXSourcesBuildPhase;
    \t\t\tbuildActionMask = 2147483647;
    \t\t\tfiles = (
    \t\t\t);
    \t\t\trunOnlyForDeploymentPostprocessing = 0;
    \t\t};
    /* End PBXSourcesBuildPhase section */

    /* Begin XCBuildConfiguration section */
    \t\t\(ids.projectDebugConfig) /* Debug */ = {
    \t\t\tisa = XCBuildConfiguration;
    \t\t\tbuildSettings = {
    \t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;
    \t\t\t\tASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS = YES;
    \t\t\t\tCLANG_ANALYZER_NONNULL = YES;
    \t\t\t\tCLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
    \t\t\t\tCLANG_ENABLE_MODULES = YES;
    \t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;
    \t\t\t\tCLANG_ENABLE_OBJC_WEAK = YES;
    \t\t\t\tCOPY_PHASE_STRIP = NO;
    \t\t\t\tDEBUG_INFORMATION_FORMAT = dwarf;
    \t\t\t\tENABLE_STRICT_OBJC_MSGSEND = YES;
    \t\t\t\tENABLE_TESTABILITY = YES;
    \t\t\t\tENABLE_USER_SCRIPT_SANDBOXING = YES;
    \t\t\t\tGCC_C_LANGUAGE_STANDARD = gnu17;
    \t\t\t\tGCC_DYNAMIC_NO_PIC = NO;
    \t\t\t\tGCC_NO_COMMON_BLOCKS = YES;
    \t\t\t\tGCC_OPTIMIZATION_LEVEL = 0;
    \t\t\t\tGCC_PREPROCESSOR_DEFINITIONS = (
    \t\t\t\t\t"DEBUG=1",
    \t\t\t\t\t"$(inherited)",
    \t\t\t\t);
    \t\t\t\t\(platform.deploymentTargetKey) = \(platform.deploymentTargetValue);
    \t\t\t\tMTL_ENABLE_DEBUG_INFO = INCLUDE_SOURCE;
    \t\t\t\tMTL_FAST_MATH = YES;
    \t\t\t\tONLY_ACTIVE_ARCH = YES;
    \t\t\t\tSDKROOT = \(platform.sdkRoot);
    \t\t\t\tSWIFT_ACTIVE_COMPILATION_CONDITIONS = "DEBUG $(inherited)";
    \t\t\t\tSWIFT_OPTIMIZATION_LEVEL = "-Onone";
    \t\t\t};
    \t\t\tname = Debug;
    \t\t};
    \t\t\(ids.projectReleaseConfig) /* Release */ = {
    \t\t\tisa = XCBuildConfiguration;
    \t\t\tbuildSettings = {
    \t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;
    \t\t\t\tASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS = YES;
    \t\t\t\tCLANG_ANALYZER_NONNULL = YES;
    \t\t\t\tCLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
    \t\t\t\tCLANG_ENABLE_MODULES = YES;
    \t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;
    \t\t\t\tCLANG_ENABLE_OBJC_WEAK = YES;
    \t\t\t\tCOPY_PHASE_STRIP = NO;
    \t\t\t\tDEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
    \t\t\t\tENABLE_NS_ASSERTIONS = NO;
    \t\t\t\tENABLE_STRICT_OBJC_MSGSEND = YES;
    \t\t\t\tENABLE_USER_SCRIPT_SANDBOXING = YES;
    \t\t\t\tGCC_C_LANGUAGE_STANDARD = gnu17;
    \t\t\t\tGCC_NO_COMMON_BLOCKS = YES;
    \t\t\t\t\(platform.deploymentTargetKey) = \(platform.deploymentTargetValue);
    \t\t\t\tMTL_ENABLE_DEBUG_INFO = NO;
    \t\t\t\tMTL_FAST_MATH = YES;
    \t\t\t\tSDKROOT = \(platform.sdkRoot);
    \t\t\t\tSWIFT_COMPILATION_MODE = wholemodule;
    \t\t\t\tVALIDATE_PRODUCT = YES;
    \t\t\t};
    \t\t\tname = Release;
    \t\t};
    \t\t\(ids.targetDebugConfig) /* Debug */ = {
    \t\t\tisa = XCBuildConfiguration;
    \t\t\tbuildSettings = {
    \t\t\t\tASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
    \t\t\t\tASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;
    \t\t\t\tCODE_SIGN_STYLE = Automatic;
    \t\t\t\tCURRENT_PROJECT_VERSION = 1;
    \t\t\t\tENABLE_PREVIEWS = YES;
    \t\t\t\tGENERATE_INFOPLIST_FILE = YES;
    \t\t\t\tLD_RUNPATH_SEARCH_PATHS = (
    \t\t\t\t\t"$(inherited)",
    \t\t\t\t\t"@executable_path/Frameworks",
    \t\t\t\t);
    \t\t\t\tMARKETING_VERSION = 1.0;
    \t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = \(bundleIdentifier);
    \t\t\t\tPRODUCT_NAME = "$(TARGET_NAME)";
    \t\t\t\tSUPPORTED_PLATFORMS = \(platform.supportedPlatforms);
    \t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;
    \t\t\t\tSWIFT_VERSION = 5.0;
    \t\t\t\tTARGETED_DEVICE_FAMILY = \(platform.targetedDeviceFamily);
    \t\t\t};
    \t\t\tname = Debug;
    \t\t};
    \t\t\(ids.targetReleaseConfig) /* Release */ = {
    \t\t\tisa = XCBuildConfiguration;
    \t\t\tbuildSettings = {
    \t\t\t\tASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
    \t\t\t\tASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME = AccentColor;
    \t\t\t\tCODE_SIGN_STYLE = Automatic;
    \t\t\t\tCURRENT_PROJECT_VERSION = 1;
    \t\t\t\tENABLE_PREVIEWS = YES;
    \t\t\t\tGENERATE_INFOPLIST_FILE = YES;
    \t\t\t\tLD_RUNPATH_SEARCH_PATHS = (
    \t\t\t\t\t"$(inherited)",
    \t\t\t\t\t"@executable_path/Frameworks",
    \t\t\t\t);
    \t\t\t\tMARKETING_VERSION = 1.0;
    \t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = \(bundleIdentifier);
    \t\t\t\tPRODUCT_NAME = "$(TARGET_NAME)";
    \t\t\t\tSUPPORTED_PLATFORMS = \(platform.supportedPlatforms);
    \t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;
    \t\t\t\tSWIFT_VERSION = 5.0;
    \t\t\t\tTARGETED_DEVICE_FAMILY = \(platform.targetedDeviceFamily);
    \t\t\t};
    \t\t\tname = Release;
    \t\t};
    /* End XCBuildConfiguration section */

    /* Begin XCConfigurationList section */
    \t\t\(ids.projectBuildConfigList) /* Build configuration list for PBXProject "\(productName)" */ = {
    \t\t\tisa = XCConfigurationList;
    \t\t\tbuildConfigurations = (
    \t\t\t\t\(ids.projectDebugConfig) /* Debug */,
    \t\t\t\t\(ids.projectReleaseConfig) /* Release */,
    \t\t\t);
    \t\t\tdefaultConfigurationIsVisible = 0;
    \t\t\tdefaultConfigurationName = Release;
    \t\t};
    \t\t\(ids.targetBuildConfigList) /* Build configuration list for PBXNativeTarget "\(productName)" */ = {
    \t\t\tisa = XCConfigurationList;
    \t\t\tbuildConfigurations = (
    \t\t\t\t\(ids.targetDebugConfig) /* Debug */,
    \t\t\t\t\(ids.targetReleaseConfig) /* Release */,
    \t\t\t);
    \t\t\tdefaultConfigurationIsVisible = 0;
    \t\t\tdefaultConfigurationName = Release;
    \t\t};
    /* End XCConfigurationList section */
    \t};
    \trootObject = \(ids.project) /* Project object */;
    }
    """
}

private func schemeXML(productName: String, mainTargetID: String) -> String {
    let container = "\(productName).xcodeproj"
    return """
    <?xml version="1.0" encoding="UTF-8"?>
    <Scheme
       LastUpgradeVersion = "1600"
       version = "1.7">
       <BuildAction
          parallelizeBuildables = "YES"
          buildImplicitDependencies = "YES">
          <BuildActionEntries>
             <BuildActionEntry
                buildForTesting = "YES"
                buildForRunning = "YES"
                buildForProfiling = "YES"
                buildForArchiving = "YES"
                buildForAnalyzing = "YES">
                <BuildableReference
                   BuildableIdentifier = "primary"
                   BlueprintIdentifier = "\(mainTargetID)"
                   BuildableName = "\(productName).app"
                   BlueprintName = "\(productName)"
                   ReferencedContainer = "container:\(container)">
                </BuildableReference>
             </BuildActionEntry>
          </BuildActionEntries>
       </BuildAction>
       <TestAction
          buildConfiguration = "Debug"
          selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
          selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
          shouldUseLaunchSchemeArgsEnv = "YES">
          <Testables>
          </Testables>
       </TestAction>
       <LaunchAction
          buildConfiguration = "Debug"
          selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
          selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
          launchStyle = "0"
          useCustomWorkingDirectory = "NO"
          ignoresPersistentStateOnLaunch = "NO"
          debugDocumentVersioning = "YES"
          debugServiceExtension = "internal"
          allowLocationSimulation = "YES">
          <BuildableProductRunnable
             runnableDebuggingMode = "0">
             <BuildableReference
                BuildableIdentifier = "primary"
                BlueprintIdentifier = "\(mainTargetID)"
                BuildableName = "\(productName).app"
                BlueprintName = "\(productName)"
                ReferencedContainer = "container:\(container)">
             </BuildableReference>
          </BuildableProductRunnable>
       </LaunchAction>
       <ProfileAction
          buildConfiguration = "Release"
          shouldUseLaunchSchemeArgsEnv = "YES"
          savedToolIdentifier = ""
          useCustomWorkingDirectory = "NO"
          debugDocumentVersioning = "YES">
          <MacroExpansion>
             <BuildableReference
                BuildableIdentifier = "primary"
                BlueprintIdentifier = "\(mainTargetID)"
                BuildableName = "\(productName).app"
                BlueprintName = "\(productName)"
                ReferencedContainer = "container:\(container)">
             </BuildableReference>
          </MacroExpansion>
       </ProfileAction>
       <AnalyzeAction
          buildConfiguration = "Debug">
       </AnalyzeAction>
       <ArchiveAction
          buildConfiguration = "Release"
          revealArchiveInOrganizer = "YES">
       </ArchiveAction>
    </Scheme>
    """
}
